services:
    sonata.admin.team:
        class: AppBundle\Admin\TeamAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Cards", label: "Team" }
        arguments:
            - ~
            - AppBundle\Entity\Team
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle]]
    sonata.admin.player:
        class: AppBundle\Admin\PlayerAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Cards", label: "Player" }
        arguments:
            - ~
            - AppBundle\Entity\Player
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle]]
    sonata.admin.tacticalsetting:
        class: AppBundle\Admin\TacticalSettingAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Cards", label: "Tactical Setting" }
        arguments:
            - ~
            - AppBundle\Entity\TacticalSetting
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle]]
    sonata.admin.position:
        class: AppBundle\Admin\PositionAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Skills", label: "Position" }
        arguments:
            - ~
            - AppBundle\Entity\Position
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle]]
    sonata.admin.perk:
        class: AppBundle\Admin\PerkAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Skills", label: "Perk" }
        arguments:
            - ~
            - AppBundle\Entity\Perk
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle]]